// This file is generated by tools/gpx_to_mc.py.
// The bundled route is only a tiny synthetic demo so the project can render
// immediately in the simulator. Replace it with your own GPX before using it.
class RouteData {
    static var NAME = "DEMO ROUTE";

    // Geographic origin used to project GPS lat/lon to local meters.
    static var BASE_LAT = 37.000000;
    static var BASE_LON = 127.000000;
    static var LAT_M_PER_DEG = 110540.0;
    static var LON_M_PER_DEG = 88904.0;

    // Local route coordinates in meters, elevation in meters, cumulative distance in meters.
    static var X = [0.0, 120.0, 260.0, 390.0, 540.0, 700.0, 860.0, 1020.0, 1180.0, 1360.0];
    static var Y = [0.0, 45.0, 120.0, 90.0, 170.0, 250.0, 210.0, 320.0, 300.0, 390.0];
    static var ELE = [120.0, 138.0, 172.0, 205.0, 250.0, 315.0, 285.0, 350.0, 325.0, 410.0];
    static var DIST = [0.0, 128.0, 287.0, 421.0, 591.0, 772.0, 943.0, 1137.0, 1298.0, 1499.0];

    static function size() {
        return X.size();
    }

    static function hasRoute() {
        return X.size() > 1;
    }
}
